export const AUTH_INIT_SUCCESS = 'AUTH_INIT_SUCCESS'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_REFRESH_SUCCESS = 'AUTH_REFRESH_SUCCESS'
export const AUTH_REFRESH_ERROR = 'AUTH_REFRESH_ERROR'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED'

export const HIDE_SNACKBAR = 'HIDE_SNACKBAR'

export const NAVIGATION_DRAWER_CHANGE = 'NAVIGATION_DRAWER_CHANGE'
export const NAVIGATION_DRAWER_TOGGLE = 'NAVIGATION_DRAWER_TOGGLE'